import image_one from '../../images/p8.jpg'
import image_two from '../../images/p9.jpg'
import image_three from '../../images/p10.jpg'
const data = {
    products: [
        {
            id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: image_one,
            price: 100,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 23,
            countInStock: 10,
            description: 'high quality product',
            save: 10,
        },
        {
            id: '2',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: image_two,
            price: 107,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 50,
            countInStock: 0,
            description: 'high quality product',
            save: 15,
        },
        {
            id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: image_three,
            price: 230,
            brand: 'Nike',
            rating: 1.5,
            numReviews: 23,
            countInStock: 75,
            description: 'high quality product',
            save: 34,
        },
        {
            id: '4',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: image_two,
            price: 150,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 23,
            countInStock: 5,
            description: 'high quality product',
            save: 10,
        },
        {
            id: '5',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: image_three,
            price: 550,
            brand: 'Nike',
            rating: 5,
            numReviews: 23,
            countInStock: 0,
            description: 'high quality product',
            save: 5,
        },
        {
            id: '6',
            name: 'Gucci',
            category: 'Shoe',
            image: image_one,
            price: 150,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 23,
            countInStock: 51,
            description: 'high quality product',
            save: 8,
        },
        {
            id: '7',
            name: 'Gucci',
            category: 'Shoe',
            image: image_three,
            price: 150,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 23,
            countInStock: 25,
            description: 'high quality product',
            save: 8,
        },
        {
            id: '8',
            name: 'Fendi',
            category: 'Shoe',
            image: image_two,
            price: 150,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 23,
            countInStock: 0,
            description: 'high quality product',
            save: 8,
        }
    ]
}

export default data;